name: zama
description: L'app del centro Zama

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/static/Raleway-Black.ttf
          weight: 900
        - asset: fonts/Raleway/static/Raleway-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Raleway/static/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway/static/Raleway-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Raleway/static/Raleway-ExtraBold.ttf
          weight: 800
        - asset: fonts/Raleway/static/Raleway-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Raleway/static/Raleway-ExtraLight.ttf
          weight: 200
        - asset: fonts/Raleway/static/Raleway-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Raleway/static/Raleway-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Raleway/static/Raleway-Light.ttf
          weight: 300
        - asset: fonts/Raleway/static/Raleway-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Raleway/static/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway/static/Raleway-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Raleway/static/Raleway-Regular.ttf
          weight: 400
        - asset: fonts/Raleway/static/Raleway-SemiBold.ttf
          weight: 600
        - asset: fonts/Raleway/static/Raleway-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Raleway/static/Raleway-Thin.ttf
          weight: 100
        - asset: fonts/Raleway/static/Raleway-ThinItalic.ttf
          weight: 100
          style: italic